//DO NOT EDIT THIS FILE

import { NextResponse } from 'next/server';
// The client you created from the Server-Side Auth instructions
import { createClient } from '@/lib/supabase/server';

export async function GET(request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get('code');
  // if 'next' is in param, use it as the redirect URL
  const next = searchParams.get('next') ?? '/dashboard';

  if (code) {
    const supabase = await createClient();
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      const forwardedHost = request.headers.get('x-forwarded-host');
      const forwardedProto = request.headers.get('x-forwarded-proto');
      const fallbackHost = request.headers.get('host') ?? new URL(request.url).host;
      const host = forwardedHost ?? fallbackHost;
      const isLocalHost = host?.startsWith('localhost') || host?.startsWith('127.0.0.1');
      const protocol = forwardedProto ?? (isLocalHost ? 'http' : 'https');
      const redirectUrl = new URL(next, `${protocol}://${host}`);

      return NextResponse.redirect(redirectUrl.toString());
    }
  }

  // return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/auth/auth-code-error`);
}
